"""Read/write the persistent pattern + struct-layout database at fd6/inject/patterns/fh6_patterns.json.

The file is the contract between the discovery tooling (which populates it) and the injector
(which consumes it). Schema is intentionally explicit so it's reviewable.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Literal


DEFAULT_PATTERNS_PATH = Path(__file__).resolve().parent / "patterns" / "fh6_patterns.json"


FieldType = Literal["f32", "u32", "i32", "u16", "i16", "u8", "i8", "rgba8", "f32_pair"]
FIELD_SIZES: dict[str, int] = {
    "f32": 4, "u32": 4, "i32": 4, "u16": 2, "i16": 2, "u8": 1, "i8": 1, "rgba8": 4, "f32_pair": 8,
}


@dataclass
class FieldSpec:
    name: str            # e.g. "x", "y", "rx", "ry", "angle", "color"
    offset: int          # byte offset within the shape struct
    type: str            # one of FieldType
    note: str = ""

    def size(self) -> int:
        return FIELD_SIZES.get(self.type, 0)


@dataclass
class ShapeStruct:
    stride_bytes: int = 0
    fields: list[FieldSpec] = field(default_factory=list)

    def field_by_name(self, name: str) -> FieldSpec | None:
        for f in self.fields:
            if f.name == name:
                return f
        return None


@dataclass
class PatternEntry:
    name: str
    pattern: str                    # AOB string with `??` wildcards
    offset_after_match: int = 0     # bytes from match start to read the displacement at
    relative_addressing: bool = True  # if True, treat the read u32 as a RIP-relative disp32
    extra_offset: int = 0           # added to the resolved address (e.g., struct member offset)
    note: str = ""


@dataclass
class PatternsFile:
    schema_version: int = 1
    game_executable: str = "forzahorizon6.exe"
    patterns: list[PatternEntry] = field(default_factory=list)
    shape_struct: ShapeStruct = field(default_factory=ShapeStruct)
    vinyl_group: dict = field(default_factory=dict)   # extra metadata: layer_count offset, shape_array_ptr offset, etc.
    discovered_at: str = ""
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "_schema_version": self.schema_version,
            "_note": self.notes or "Generated by forza_abyss_painter.inject discovery tooling.",
            "game_executable": self.game_executable,
            "discovered_at": self.discovered_at,
            "patterns": [asdict(p) for p in self.patterns],
            "shape_struct": {
                "stride_bytes": self.shape_struct.stride_bytes,
                "fields": [asdict(f) for f in self.shape_struct.fields],
            },
            "vinyl_group": self.vinyl_group,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "PatternsFile":
        ss_raw = d.get("shape_struct", {}) or {}
        ss = ShapeStruct(
            stride_bytes=int(ss_raw.get("stride_bytes") or 0),
            fields=[FieldSpec(**fs) for fs in ss_raw.get("fields", []) or []],
        )
        pats = [PatternEntry(**pe) for pe in d.get("patterns", []) or []]
        return cls(
            schema_version=int(d.get("_schema_version", 1)),
            game_executable=str(d.get("game_executable", "forzahorizon6.exe")),
            patterns=pats,
            shape_struct=ss,
            vinyl_group=d.get("vinyl_group", {}) or {},
            discovered_at=str(d.get("discovered_at", "")),
            notes=str(d.get("_note", "")),
        )


def load_patterns(path: str | Path = DEFAULT_PATTERNS_PATH) -> PatternsFile:
    p = Path(path)
    if not p.exists():
        return PatternsFile()
    with open(p, "r", encoding="utf-8") as f:
        data = json.load(f)
    return PatternsFile.from_dict(data)


def save_patterns(pf: PatternsFile, path: str | Path = DEFAULT_PATTERNS_PATH) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(pf.to_dict(), f, indent=2)
    return p


def has_usable_patterns(pf: PatternsFile | None = None) -> bool:
    pf = pf or load_patterns()
    return bool(pf.patterns) and pf.shape_struct.stride_bytes > 0 and bool(pf.shape_struct.fields)
